name: Petshop workflow
on: push

jobs: 
  build:
    name: Node Build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        uses: ./.github/actions/node
